version: '3.8'

services:
  app:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - PORT=8080
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  react_app:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ""
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
      - react_app
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
